# Configure these following properties before start the application
client-id:
client-secret:
tenant-id:
vault-uri:

spring:
# Do not configure these following properties
#  cloud:
#    azure:
#      keyvault:
#        secret:
#          property-source-enabled: true
#          property-sources:
#            - name: key-vault-property-souece-1
#              endpoint: ${ENDPOINT_1}
#            - name: key-vault-property-souece-2
#              endpoint: ${ENDPOINT_2}
  profiles:
    active: develop
